---
abstract: 'A moose class that abstracts Net::OAuth for you'
author:
  - 'Ben Hengst <notbenh@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-Easy
requires:
  Carp::Always: 0
  Crypt::OpenSSL::RSA: 0
  Data::Validate::URI: 0
  Digest::MD5: 0
  File::Slurp: 0
  Moose: 0
  Net::OAuth: 0
  Test::Most: 0
  Test::WWW::Mechanize: 0
version: 0.001_02
